name: GitHub Actions Demo
on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/**'
  pull_request:
    branches:
      - main
  schedule:
    - cron: '15 6 * * 0'  # Every Sunday at 06:15 UTC
    workflow_dispatch:
      inputs:
         environment:
          description: 'Environment to deploy to'
          type: environment
          required: true      # Allows manual triggering

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:

      - name: Event that triggered workflow
        run: |
          echo  "The job was triggered by event: ${{ github.event_name }}"
          echo  "The job name of you branch is ${{ github.ref }}"

      - name: Checkout
        uses: actions/checkout@v6.0.2

      - name: List files using ls command
        run: |
          echo "The repo is ${{ github.repository }} and files are"
          tree
